import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { executions } from "@/lib/data"
import { ArrowUpRight } from "lucide-react"
import Link from "next/link"

export function RecentIOTable() {
  const recentExecutions = executions.slice(0, 5);
  return (
    <div className="grid gap-4 md:grid-cols-2">
      <Card>
        <CardHeader className="flex flex-row items-center">
          <div className="grid gap-2">
            <CardTitle>Recent Inputs</CardTitle>
            <CardDescription>
              Latest inputs processed by your automations.
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Flow</TableHead>
                <TableHead className="text-right">Type</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {recentExecutions.map(exec => (
                <TableRow key={exec.id}>
                  <TableCell>
                    <div className="font-medium">{exec.flowName}</div>
                    <div className="text-sm text-muted-foreground">
                      {new Date(exec.timestamp).toLocaleString()}
                    </div>
                  </TableCell>
                  <TableCell className="text-right">
                    <Badge variant="outline" className="capitalize">{exec.input.type}</Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
      <Card>
        <CardHeader className="flex flex-row items-center">
          <div className="grid gap-2">
            <CardTitle>Recent Outputs</CardTitle>
            <CardDescription>
              Latest outputs generated by your automations.
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Flow</TableHead>
                <TableHead className="text-right">Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {recentExecutions.map(exec => (
                <TableRow key={exec.id}>
                  <TableCell>
                    <div className="font-medium">{exec.flowName}</div>
                    <div className="text-sm text-muted-foreground">
                      {new Date(exec.timestamp).toLocaleString()}
                    </div>
                  </TableCell>
                  <TableCell className="text-right">
                    <Badge variant={exec.status === 'Success' ? 'default' : 'destructive'} className={exec.status === 'Success' ? 'bg-green-500' : ''}>
                      {exec.status}
                    </Badge>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
